import type { Metadata } from "next";
import "@/app/globals.css";
import { acme } from "@/app/ui/fonts";
import { SideBar } from "@/app/ui/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${acme} antialiased`}>
        <div className="flex h-screen flex-col md:flex-row ">
          <div className="w-full flex-none md:w-64 bg-bgNavColor">
            <SideBar />
          </div>
          <div className="flex-grow w-pageScreen ">{children}</div>
        </div>
      </body>
    </html>
  );
}
